apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dave-deployment
  labels:
    app: dave
    project: dave
  namespace: demo
spec:
  replicas: 3
  template:
    metadata:
      name: dave
      labels:
        name: dave
        project: dave
    spec:
      containers:
        - image: scholzj/dave:demo
          name: dave
          imagePullPolicy: Always
          env:
            - name: DAVE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: log.level
            - name: DAVE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: db.name
            - name: DAVE_DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: db.hostname
            - name: DAVE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: db.port
            - name: DAVE_HTTP_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.enable
            - name: DAVE_HTTP_COMPRESSION
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.compression
            - name: DAVE_HTTP_REDIRECT
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.redirect
            - name: DAVE_HTTP_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.redirectUri
            - name: DAVE_HTTP_AUTH
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.auth
            - name: DAVE_HTTP_CORS
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.cors
            - name: DAVE_HTTP_CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: dave-config
                  key: http.cors_origin
            - name: DAVE_HTTP_AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: dave-secret
                  key: http.auth_salt
            - name: DAVE_HTTP_SSL_SERVER_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: dave-secret
                  key: http.public_key
            - name: DAVE_HTTP_SSL_SERVER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: dave-secret
                  key: http.private_key
            - name: DAVE_HTTP_JWT_BASE64_KEYSTORE
              valueFrom:
                secretKeyRef:
                  name: dave-secret
                  key: jwt.keystore
            - name: DAVE_HTTP_JWT_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dave-secret
                  key: jwt.keystore_password
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8181
              name: https
